# Generated by Django 3.1.4 on 2020-12-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='math', max_length=250),
            preserve_default=False,
        ),
    ]
